### ISSUE TITLE
Final group capstone: Kanban board setup

### ISSUE THREAD

**Issue by Kaiserabbas** [Kaiserabbas/motorcycle_booking_back_end#20]
## Created cards based on [the project requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/business_requirements.md). 

- Each task is a separate card that:
- Has a descriptive title.
- Has the number of points in the [Xpt] prefix. That number indicates the number of points.
- Has a description of the task.

## Coding Partnes
1. @Kaiserabbas 
2. @Graciano1997 
3. @Zel-hub7 
4. @albertkantwi 
5. @pushkar1995

## Back-End 
[Backend](https://github.com/Kaiserabbas/motorcycle_booking_back_end)
## Front-End 
[Frontend]( https://github.com/Kaiserabbas/motorcycle_booking_front_end)

## Kanban-Board 
[Kanban Board](https://github.com/users/Kaiserabbas/projects/6)
![image](https://github.com/Kaiserabbas/motorcycle_booking_back_end/assets/123939543/e02a4bcc-fe42-4d77-8397-799348ce3fb5)
g-

**Comment by Meltrust** [comment]
Hi,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

1- You have submitted a project, that does not contain a screenshot of the Kanban board.  

2- **Also, the kanban board is not public, so I can't access it.**

![image](https://github.com/Kaiserabbas/motorcycle_booking_back_end/assets/57421823/fbf15fb2-904d-4011-baa0-a622a55101ad)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All tasks have descriptions✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] According to the project requirements:

![image](https://github.com/Kaiserabbas/motorcycle_booking_back_end/assets/57421823/b186d408-a878-43b9-8eb1-71c2d915a8f4)

At the time of this review, the pointings are:

21 Zel-hub7
27 pushkar1995
23 Kaiserabbas
23 Graciano1997
23 albertkantwi

@pushkar1995 has more than five points than @Zel-hub7 because 27 - 21 = 6

Kindly, make it so nobody on the team has more than 5 points than any other person.

That way, we can meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md). 

- [ ] According to the project requirements:

![image](https://github.com/Kaiserabbas/motorcycle_booking_back_end/assets/57421823/d4f038cb-3366-456c-b475-1247a1b16f44)

This task does not have any points assigned:  

![image](https://github.com/Kaiserabbas/motorcycle_booking_back_end/assets/57421823/5abd3d31-695e-49fe-8818-c1a8f40539c3)

Kindly, either add some points to this task or remove it from the board (do not remove the GitHub issue). 👍 

_tip: In the software industry, we _never_ add the creation of the board itself as a project task._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Meltrust** [comment]
## Wow, you did it 🎉
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for implementing the changes requested by the previous reviewer 💪 🥇 ㊗️ 
### Well done!




Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- Pointings are now equal✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
